# Generated by Django 5.2.9 on 2025-12-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20)),
                ('outstanding_amount', models.FloatField()),
                ('overdue_days', models.IntegerField()),
                ('assigned_dca', models.CharField(max_length=50)),
                ('recovery_prediction', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('recovery_probability', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Escalated', 'Escalated'), ('Closed', 'Closed')], max_length=20)),
            ],
        ),
    ]
